s3:
  enabled: true
  logs:
    accessKey: "seaweedfs_rw_access"
    secretKey: "seaweedfs_rw_secret"
  createBuckets:
    - name: "risingwave-bucket"
    - name: "iceberg-bucket"
master:
  replicas: 1
volume:
  replicas: 1
filer:
  replicas: 1
